### ISSUE TITLE
[Bug]: mushroom.js:298 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by pganansia** [piitaya/lovelace-mushroom#1611]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Since few I get this error message using mushroom-template-card 
mushroom.js:298 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')
    at e.value (mushroom.js:298:27939)
    at e.value (mushroom.js:6:7140)
    at e.value (mushroom.js:6:6885)
    at e.value (mushroom.js:6:6024)
    at e.<anonymous> (mushroom.js:6:5743)
    at u (mushroom.js:1:4109)
    at Generator.<anonymous> (mushroom.js:1:5452)
    at Generator.next (mushroom.js:1:4538)
    at _r (mushroom.js:1:10015)
    at a (mushroom.js:1:10219)

In mushroom.js, the error is on 
![image](https://github.com/user-attachments/assets/37b2449f-e3ac-4c0a-a95e-1a52ac720ab7)

The other mushroom cards are not producing error.
Am I doing something wrong ?

Rgds.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.12.4
- Mushroom:4.2.1
```

**Comment by pganansia** [comment]
I made others tests.
It seems that this happened only when I am using custom:mushroom-template-card through a streamline card (streamline card is remplacing declutterring card) and only for the custom-mushroom-tempalte-card.
The other mushroom cards are not affected.
Rgds

**Comment by pganansia** [comment]
I apologized, it was a bug generated by custom:Streamline-card.
It is corrected now
I close the issue.
Rgds
